Repository SOPT-31-3/Triple-iOS, pull requests merged in 2022-12, with the labels that each got.

#21 [Setting] #19 - 서버 통신 세팅
  Triple-iOS/Triple-iOS.xcodeproj/project.pbxproj
  Triple-iOS/Triple-iOS/Network/APIService/APIService.swift
  Triple-iOS/Triple-iOS/Network/Base/Encodable.swift
  Triple-iOS/Triple-iOS/Network/Base/Environment.swift
  Triple-iOS/Triple-iOS/Network/Base/NetworkLoggerPlugin.swift
  Triple-iOS/Triple-iOS/Network/DataModel/DataModel.swift
  Triple-iOS/Triple-iOS/Network/Router/Router.swift
  Triple-iOS/Triple-iOS/Resource/Support/Info.plist
Labels: 미미, Settig

#22 [Feat] #20 myTravleView 구현
  Triple-iOS/Triple-iOS.xcodeproj/project.pbxproj
  Triple-iOS/Triple-iOS/Screen/Hoho/TravelView/MyTravelModel.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TravelView/MyTravelViewController.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TravelView/TravelHeaderView.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TravelView/TravelTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/TabBar/MyTravelViewController.swift
Labels: 호호, Feat

#25 [Feat] 여행 일정 API 작성
  Triple-iOS/Triple-iOS.xcodeproj/project.pbxproj
  Triple-iOS/Triple-iOS/Network/Dto/CityModel.swift
  Triple-iOS/Triple-iOS/Network/Dto/UserRequestDto.swift
  Triple-iOS/Triple-iOS/Network/Dto/UserResponseDto.swift
  Triple-iOS/Triple-iOS/Network/Router/Router.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/Cell/CityCollectionViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/Cell/PlanTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/Model/SampleModel.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/View/PlanFooterView.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/View/PlanHeaderView.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/ViewController/CityGridViewController.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/ViewController/PlanViewController.swift
Labels: 두두, Feat
