Repository SOPT-31-3/Triple-iOS, pull requests merged in 2022-11, with the labels that each got.

#7 [Docs] Readme 수정
  README.md
Labels: 미미

#9 [Feat] #5 - home 뷰의 테이블뷰 셀 구현
  Triple-iOS/Triple-iOS.xcodeproj/project.pbxproj
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage1.imageset/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage1.imageset/IMG_9052.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage1.imageset/IMG_9052@2x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage1.imageset/IMG_9052@3x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage2.imageset/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage2.imageset/IMG_9059.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage2.imageset/IMG_9059@2x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/5차 세미나 _ 클디서 합동 세미나 (디자인 작업물)/tokyoImage2.imageset/IMG_9059@3x.png
  Triple-iOS/Triple-iOS/Screen/Hoho/HomeViewController.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/Support/Adjusted.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/Support/GetClassName.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/IconTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/MagazineTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/PopularTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/RecentTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/TokyoTableView/TokyoCollectionViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/TokyoTableView/TokyoImageModel.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/TableViewCells/TokyoTableView/TokyoTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/TabBar/MyProfileViewController.swift
Labels: 호호, Feat

#14 [Chore] #12 - 도시 선택 컬렉션뷰 수정
  Triple-iOS/Triple-iOS/Screen/Dodo/CityCollectionViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/CityGridViewController.swift
Labels: Chore, 미미

#16 [Feat] #13 - 일정 작성 뷰 구현
  Triple-iOS/Triple-iOS.xcodeproj/project.pbxproj
  Triple-iOS/Triple-iOS/Global/Constant/Image.swift
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/circle.imageset/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/circle.imageset/circle.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/circle.imageset/circle@2x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/circle.imageset/circle@3x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/friend.imageset/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/friend.imageset/friend.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/friend.imageset/friend@2x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/friend.imageset/friend@3x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/menu.imageset/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/menu.imageset/menu.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/menu.imageset/menu@2x.png
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/menu.imageset/menu@3x.png
  Triple-iOS/Triple-iOS/Screen/Dodo/CityCollectionViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/CityGridViewController.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/PlanFooterView.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/PlanHeaderView.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/PlanTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/PlanViewController.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/SampleModel.swift
Labels: 두두, Feat

#18 [Chreo] #17 - 레이아웃, 화면 전환 이슈 해결
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/else/AccentColor.colorset/Contents.json
  Triple-iOS/Triple-iOS/Resource/Asset/Assets.xcassets/else/AppIcon.appiconset/Contents.json
  Triple-iOS/Triple-iOS/Screen/Dodo/CityGridViewController.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/PlanTableViewCell.swift
  Triple-iOS/Triple-iOS/Screen/Dodo/PlanViewController.swift
  Triple-iOS/Triple-iOS/Screen/Hoho/HomeViewController.swift
Labels: Chore, 미미
